set number

let python_highlight_all=1
syntax on
syntax enable
set clipboard+=unnamed
"Set encoding and line numbering
set encoding=utf-8
set nu rnu
"
" indent when moving to the next line while writing code
set autoindent
"
" " expand tabs into spaces
set expandtab
"
" " when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4
"
" " show a visual line under the cursor's current line
set cursorline
"
" " show the matching part of the pair for [] {} and ()
set showmatch
"
"" make backspace override other  settings
set backspace=2

"" show file name in statusline
set laststatus=2
set statusline=%f "tail of the filename

"" add a ruler at 79 characters
set colorcolumn=79
highlight ColorColumn ctermbg=0
